sudo: required
services:
  - docker

before_install:
  - docker build -t sam821122/practice -f Dockerfile.dev .

script:
  - docker run -e CI=trrue sam821122/practice npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "sam-deploy-practice"
  env: "Sam-deploy-practice-env"
  bucket_name: "elasticbeanstalk-us-east-1-857539534421"
  bucket_path: "sam-deploy-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
